/******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the XMC MCU: CCU4 Capture Example
*              for ModusToolbox.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2015-2021, Infineon Technologies AG
* All rights reserved.                        
*                                             
* Boost Software License - Version 1.0 - August 17th, 2003
* 
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
* 
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*                                                                              
*****************************************************************************/

#include <stdio.h>
#include "cybsp.h"
#include "cy_utils.h"
#include "cy_retarget_io.h"

/*******************************************************************************
* Macros
*******************************************************************************/
/* Define macro to enable/disable printing of debug messages */
#define ENABLE_XMC_DEBUG_PRINT              (0)

/* Define macro to set the loop count before printing debug messages */
#if ENABLE_XMC_DEBUG_PRINT
#define DEBUG_LOOP_COUNT_MAX                (1U)
#endif

/* Event mapping for CAPTURE_0 */
#define CAPTURE_0_EVENT_RISING_EDGE  XMC_CCU4_SLICE_IRQ_ID_EVENT0
#define CAPTURE_0_EVENT_FALLING_EDGE XMC_CCU4_SLICE_IRQ_ID_EVENT1

/* Every time that a capture trigger 0 occurs, CCcapt0, the actual value of the 
 * timer is captured into the capture register 1 and the previous value stored in 
 * this register is transferred into capture register 0 */
#define CAPTURE_0_VALUE_RISING_EDGE  1

/* Every time that a capture trigger 1 occurs, CCcapt1, the actual value of the 
 * timer is captured into the capture register 3 and the previous value stored in 
 * this register is transferred into capture register 2 */
#define CAPTURE_0_VALUE_FALLING_EDGE 3

/*******************************************************************************
* Function Name: main
********************************************************************************
* Summary:
* This is the main function. It performs initial setup of the device, 
* and starts the CCU4 slices. The main while loop checks whether the CAPTURE_0
* has detected a rising or falling edge at its input and prints the corresponding 
* captured timer value.
*
* Parameters:
*  none
*
* Return:
*  int
*
*******************************************************************************/
int main(void)
{
    cy_rslt_t result;

    /* Initialize the device and board peripherals */
    result = cybsp_init() ;
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /* Initialize retarget-io to use the debug UART port */
    cy_retarget_io_init(CYBSP_DEBUG_UART_HW);

    #if ENABLE_XMC_DEBUG_PRINT
    printf("Initialization done\r\n");
    #endif

    /* Start CCU4 slices */
    XMC_CCU4_SLICE_StartTimer(CAPTURE_0_HW);
    XMC_CCU4_SLICE_StartTimer(PWM_0_HW);
  
    /* Print starting sequence on screen */ 
    printf("XMC CCU4 Capture example\r\n");
    printf("========================\r\n");
    printf("Starting counters...\r\n");
    
    /* Variables define to get captured timer value on input signal rising and falling edge */
    uint16_t capture_rising;
    uint16_t capture_falling;

    while (1)
    {
        /* Check for a rising edge event in the input signal */
        if (XMC_CCU4_SLICE_GetEvent(CAPTURE_0_HW, CAPTURE_0_EVENT_RISING_EDGE))
        {
            /* Clear event*/
            XMC_CCU4_SLICE_ClearEvent(CAPTURE_0_HW, CAPTURE_0_EVENT_RISING_EDGE);

            /* Get captured timer value on input signal rising edge */
            capture_rising = XMC_CCU4_SLICE_GetCaptureRegisterValue(CAPTURE_0_HW, CAPTURE_0_VALUE_RISING_EDGE);
           
            /* Print captured timer value of input signal rising edge */
            printf("Rising edge: %d\r\n", capture_rising);
        }

        /* Check for a falling edge event in the input signal */
        if (XMC_CCU4_SLICE_GetEvent(CAPTURE_0_HW, CAPTURE_0_EVENT_FALLING_EDGE))
        {
            /* Clear event*/
            XMC_CCU4_SLICE_ClearEvent(CAPTURE_0_HW, CAPTURE_0_EVENT_FALLING_EDGE);
            
            /* Get captured timer value on input signal falling edge */
            capture_falling = XMC_CCU4_SLICE_GetCaptureRegisterValue(CAPTURE_0_HW, CAPTURE_0_VALUE_FALLING_EDGE);
            
            /* Print captured timer value of input signal falling edge */
            printf("Falling edge: %d\r\n", capture_falling);
        }
    }
}

/* [] END OF FILE */
